customconfig.settings:
  type: config_object
  label: 'Custom config Settings'
  mapping:
    assets_paths:
      type: string
      label: 'Assets paths'
    assets_type:
      type: string
      label: 'Assets type'     
